#!/usr/bin/env bash
# Generate a production .env from scratch:
#   - random JWT_SECRET and DB_PASSWORD (you never type these)
#   - prompts for the two login passwords (blank = generate & print one)
# Re-run safe: refuses to clobber an existing .env unless you pass --force
# (the old file is backed up either way).
set -euo pipefail
cd "$(dirname "$0")/.."   # project root

ENV_FILE=".env"
if [[ -f "$ENV_FILE" && "${1:-}" != "--force" ]]; then
  echo "✗ $ENV_FILE exists. Re-run with --force to replace it." >&2
  exit 1
fi
[[ -f "$ENV_FILE" ]] && cp "$ENV_FILE" "$ENV_FILE.bak.$(date +%s)" && echo "↳ backed up existing .env"

command -v openssl >/dev/null || { echo "✗ openssl is required" >&2; exit 1; }
gen() { openssl rand -hex "${1:-32}"; }

JWT_SECRET="$(gen 32)"
DB_PASSWORD="$(gen 16)"

read -rsp "Login password for 'max'     (blank = random): " P1; echo
[[ -z "$P1" ]] && P1="$(gen 9)" && echo "  ↳ generated: max / $P1"
read -rsp "Login password for 'partner' (blank = random): " P2; echo
[[ -z "$P2" ]] && P2="$(gen 9)" && echo "  ↳ generated: partner / $P2"

read -rp "Household name in the sidebar [Mäxchen]: " HH; HH="${HH:-Mäxchen}"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-env.sh on $(date)

# Docker image tag pulled from GHCR (default: latest). Pin a SHA for reproducible deploys.
#IMAGE_TAG=latest

# Database
DB_URL=jdbc:postgresql://db:5432/homebase
DB_USER=homebase
DB_PASSWORD=$DB_PASSWORD

# JWT signing secret
JWT_SECRET=$JWT_SECRET

# The two fixed login users (re-seeded on every backend start)
SEED_USERS=max:$P1,partner:$P2

# Sidebar label
HOUSEHOLD_NAME=$HH

# Note image uploads
UPLOAD_DIR=/data/uploads
MAX_UPLOAD_MB=10

# Telegram daily digest (optional — leave blank to disable)
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=
DIGEST_TIME=20:00
EOF

chmod 600 "$ENV_FILE"
echo "✓ wrote $ENV_FILE (chmod 600). Log in with  max / $P1."
